apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBCz+tUf+P0Vc2VBEK1LkOwRTWjft6dlVZ5ukD2rrpNgmBVwm5peOYWjmV7yrAukCu2EBZs0g5b7QLXCZwz+FC1MV3oWHlay6gU7kFoMjQAsJyB1cTvITIxlnm7Y4rxxz2mkDN9V9nFHT/NW6Yesek7fRNIgHVKhDi3p168RS5yvhTHXInqe5Equ73IMCQpdqS21M/CNFV1YQIG00JKWdaGMSp2vDe3UrSxl2jdyOJG+HEcpPG3iiP4A8t8/Ls2iFkkFNua5CyaAY5G7g7Dk+5CXqAoMzxV4YkQ0E09+4og2YdbFfgF4Wl/sweaxL1C0K0jcgOYGDkGonCaUybpAgw219S5OVGjx3uRlCalaZxuyo69ugLCDWzuzM6Dcj+qyZDsZNFU5BFqLgFYHKtUd9dgWwsDUlttpVdNh+9Jej9eIs34vwWjjdfJiYBDM6JBBtrN1KWFAeNQPzdBeEYq1mKpEs9gHtf7zYJ/P9Elf018WO6BbHYPK1RkJc09hDrwrqGEbPXoA2thaaUnZOkOH3lozRVuA8ddo+GP2ESPwm1e9zQT8gmzZBS3OIHi3HckQaPCLsQwLso3Znr0KebRyq8u5maSqmjSj+shZ1px9lTU5gbQ2mpQASL83ITBQHMhQDT6BIe0lHtshkoZCh/mHiZ9unh5yxa7Tb/uvkHaT26nJJmk+MO8GtkOjcSB3jyIREa0zNUCjVmK4oHbv++v5Y5msn/gA6nlUBRhklhPDaRKpdVRYAn2+rBg
    username: AgCMn7V7Jlkg2HL9cRIs9A4J8z/u4RJu8tPRxWw9Rluh2L+55JqtkVjez120sazdFXCIpECz9cr8wlzbWHnnS1SafsH5ZM7nlDkICqFWHS7TNrpHuBr4oyHA4Vai67ZBreLUBR3RuyN2OWSvgJSn6yyaTdEGlsjY8fni4zjXkRrV6zYv0YswIH6DoIoGmviekklvoiiiJEyANuqTDBg///6jngR3KmR4LTNlSrQyq+Y+HZ1M7A7QW/B5v9MG17fpDxyXwnGrlNz6NPPGtcrpTYzXDC21amzfDWt+zTbeiOwaSF/tNwfvBKWksWWoJE2zi3/BqC4ad9VmnRYCGY6fYLb7BuWCe2WpiXQkFL63+xL/NRaFJ1i0pxWBXw7+T1lyYflpmQgqc8TL352lOjVTM9ANoUO/KsDczW7T0VRe9ZT8ZTj2G5WrfyeIj2yv/KYAEXd7wHD5Jp8RGTHLkCOe2AKy3tCm+py77M1FchtBtCWDNxkzYixv/tRQlVowPmRr0aUmiHnf6KJmFC/N92PTbJNC0q708bnT9MCPnNq45Agv5sjMd835L8Xn7G+Yxw1sM7NUkS4hPWSWnA2fX59W+pyMKZJgjBue2dsLBZFjXKx+/JDbPFSEujrCZfZCjW7gy7wue4mBOfXcWJYqYN2bSY6lY5hhLgZlBAQ1A7JIrpWfs2c3IYimYYVAiKWULEqOwi8kHsInVHT+
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

