apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgBAeDTNvCDqnkFvjqrfk0AOOlXZBUJBV1PzmS5jPd6E03vZ31f7iIrLKsSbK7gJlkUt20Vn6elZefgZws4dSbI9vPWDZqKlz8JaoF9eNEC9zJWaUWNsweOwnv9uL09q/a6h3/nxEyAQIfUJbC4c7MWvsreKTh3Olo6GSp8+1459HFIUrRdf6GNv2ixPjAUsnNweQ8slc9Y+GJVZGcKcEptCIQCb0w6Ewi2enr4W3dMXd3CaG8CvQhxh0QG5J3LF7zzjNNVPlbF2i++SAB2rWmICZA2zzMfq8bnNMm1HipxHhgs7kIh6dRDHICFyyTQJlK/cGw3ljbPZNlumjsoDJuruLSutWp3P7vw9eFtdOOtFL6ZBPBe77atE9Gw2BcCwoOovGg4u/EjjkjX5Zz1js5KMdL1uf8CsAskmAz4AZ9+IjAPABWGJN/K7NqGQhEL+pbgc1HtewkyOmD2i+cTWaC1ViFo4Gf0S+LdNylPA8CUREla1uQn1jkwsFfLCuWkkgTd9QVBC2ev5GTm/L1Mv/Rl+xcmhc3icyUz/auvsO+RiZLlmfG1qzBmdovveKoya52h+AzjZAFBl6t+C3bKwA4lamXIwCvY/7zEcZcV0Mn5wAoOKTxzkzPC5um+XqEikpS4xqY9GSwM/r3/PmISbGjZzqo9NDPxYMYQ+QNsKf4pnC9jHG8nFZsVJFQE0cnFuMCLdn4+SfLLOmwGDeUrv+x4j5pTJ5mdIZF06vMCRaVS74lUNyXfEFTcImmcKxT3DtfppTp2UYG01EDJUdEHdn0Sy+SdK0v3hOMudkOXV04irkqbnZDAS9QWS1SjzyGkSOqt89P5OAXG/x4OtNievV39bOf4DICh+QbVVn4H/i3gfTUdVy8zmFAI7J5bG70juN/ZmNbrqWOAIOJy9nQespzv9cTjbkQc3PDI9RSpZ5caplMedgakT5OZ9fldSSKV26iOzgttENLxIHzT5Gj0tf2/n0KiI3bqPfcIcRW5/d2DYKfpqT6EyYBwKPX4QJkvcfQU7teeqRJE3luaMXYtWxlriCssR8g+C4mDRw7/cLONJOJg5kkpWOl2yXvutAa4823ahhv/d9QiJnPaRi7NOZwPW9HwIon95NAA7XqzcfcQ9RFFiQuAtjDd8ERtNo03tn1jw+65v19dHOQWR3P3wqV3iUy0xcd991UgxRhHXpPS7RJi4aVYOmw4qzLZt+9k6m9sE4D9Z9RH0IeMawhEDfnVdENF5TNMX6taQVY9aAAArYISYcbj8+phxnd8SuaXdE+xd3oRpBukMEZUQLsNedFbAb+5juAuCXTYElmtNk0ALgXnXccUhdsgOOe+BVaT2cQP0ursrccnYTBROR5d4+baLuGOZ6VYEhuRxINFnHlNibBgxMq3U
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

