apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-passwords
  namespace: tools
spec:
  encryptedData:
    CLIENT_SSL_KEY_STORE_PASSWORD: AgBUfUbwF0ulDw7xvcu+x3azPk+Qy+bSSPPBWt45+7ykC/QKL5QEa4YA26WAiorl0bDKAQFzZTwlwfEz8X8eYMYNQL/g2YBMfZdFDSS2FXl9MOYrEUcobaFDdX+U/sS2Q/BaZWF//O9cdMAW6pHkC5QJvGPLWtde2LfqATt0nRwp7Kaqv1EsHVOpCG6/m/8rjWMKeREGqNEq3ik5e5uC9rb10/M6th7UzDySiCfyc3gZdHEZcJrBx2K1Rm0pevYHWWSyS4GEgEtLO2cVF1LWr7YqYOmfuWgODFWYBRdzRHQZ6jyajrGRaB8ClB3VXkYRLOggkCtTEL1J2SU7qWeaG0do5k9030PXodecLkxyYOo9dpxzFUaVQViFn41z53I/Qh1RN1PEb5okDU745XzR6l/yeooDmFa2G+Ej5dsFnDKbKtI15zWQ25XAAT08ZorMGDmuEvT2SvQfp32xaJRuZrz99PsuYOnIrZQLSAzCytM1CPHPPc9rhkORONwtTNj0BhYDfu03zIPh0r65livbPQ1PL9gcJsy+2BfdXKQB9InacsVUG/mk7Sh3fvzjUrBiD98/IDkBdcEOirZv1WLNjLTbCCSLbFm/LjGUcVaRrlaV/Pq7Y5t9wDdic9IwX2uS6Jy2sJZKA6iO8hyZOhPF+KfuucNziVBYiyAE56EJC3bBspGYErjXwjf8pxppdy0NXMXTLxSgW/olCg==
    CLIENT_SSL_TRUST_STORE_PASSWORD: AgDLyZ6x0ClQ4qD8BprrUu0uhs6G+sJXu+ipUbiFIWJbxruEpm/BSOZ9ql1vSxDnNIe4ZeXuZhcGh6feAWvVApumFQujf9WOZnMGI/7Nq/RPTvsaKGl/G7UdIdRTl7ctAKv+maacXxBannmE4BE9thCY8I/RjZGsXwmNRyweJFQVPRzdyzXueWFWu5WVTkC8STI+GNdzsLq4uQteCSGUFpM7tNeIceo7CPCEwmaWfi3qewdpsQa5yHkNUBE5eP/d69P089EiC1tEGUhhzTN3d2oJV3xZfBxvN3r4Oa9UDnKjzF0OajPYV7uyK+bZviZtSo3yKIL7VrODaarv7hpWqWrDLuGqOhZJC8JtWAJjeezEqnIR668Hi+py2EMKLQjN/dt+97lGfDE1k0YkamJVi8Hy3tqkxZhF/4ECfbRleVO+lNJ9owyURtNq7FbI+8psEf37dSAfi9ZMTWLHI9EzErEC7t2UDuInC12RcQI1MDY8+eKcW1IqRkrHVGqEcfg/iYPjpTGI7qupmmi3GccwJgSdEUSE1PGVto+xDLPuEs/InlK7zchqnB6YvTxrJtMxQ5lzjnpDCB06Y9MZqKzxSFuV0L0EV+xoSF3canS4380ul5GVrLT/I31fdsj/MLeGAaR3dUJcivqaWn9/dubt1CdzBV+KiFmRIbFHl/ISlHHqFDSr1Q4MRsNz2P3WJm8J8oWD9+CFh+fJaw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-passwords
      namespace: tools
    type: Opaque

